/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form;

import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import com.github.sarxos.webcam.WebcamResolution;
import com.raven.Service.HoaDonService;
import com.raven.Service.SanPhamChiTietSV;
import com.raven.Service.*;
import com.raven.formTT.KhachHangJDialog;
import com.raven.model.SanPhamChiTiet;
import java.util.ArrayList;
import com.raven.model.*;
import java.awt.Dimension;
import java.lang.reflect.Array;
import java.math.BigDecimal;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import java.util.concurrent.Executor;
import java.util.concurrent.Executors;
import java.util.concurrent.ThreadFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utils.Auth;

/**
 *
 * @author admin
 */
public class Form_Ban_Hang extends javax.swing.JPanel {
    DefaultTableModel modelSP;
    DefaultTableModel modelHD;
    DefaultTableModel modelGH;
    SanPhamChiTiet spct= new SanPhamChiTiet();
    SanPhamChiTietSV spctsv= new SanPhamChiTietSV();
    List<SanPhamChiTiet> listspct=new ArrayList<>();
    Model_SanPham sp= new Model_SanPham();
    SanPhamService spsv= new SanPhamService();
    List<Model_SanPham> listSP= new ArrayList<>();
    Model_Hoa_Don hd= new Model_Hoa_Don();
    HoaDonService hdsv= new HoaDonService();
    List<Model_Hoa_Don> listhd= new ArrayList<>();
    private static List<GioHang1> listGioHang=new ArrayList<>();
    Model_SanPhamChiTiet ctsp= new Model_SanPhamChiTiet();
    List<Model_SanPhamChiTiet>listctsp= new ArrayList<>();
    SanPhamChiTietService ctspsv= new SanPhamChiTietService();
        Date thoiGianHienTai = new Date();
    Model_HoaDonChiTiet hdct= new Model_HoaDonChiTiet();
    List<Model_HoaDonChiTiet> listHDCT= new ArrayList<>();
    HoaDonCTService hdctsv= new HoaDonCTService();
     List<modelGioHang> listMGioHang = new ArrayList<>();    
     HoaDon hoadon= new HoaDon();
     HoaDonChiTiet cthd= new HoaDonChiTiet();
     HoaDonChiTietService cthdsv= new HoaDonChiTietService();
     

    /**
     * Creates new form form_Ban_Hang
     */
    
    public Form_Ban_Hang() {
        initComponents();
        modelSP=(DefaultTableModel) tblDanhMucSP.getModel();
        modelHD=(DefaultTableModel) tblDanhMucHD.getModel();
        modelGH=(DefaultTableModel) tblGioHang.getModel();
        listspct= spctsv.selectSPCTBanHang();
        listhd=hdsv.selectALllHoaDonBH();
        modelGH.setRowCount(0);
        loadCBB();
        showDataDanhMucSP(listspct);
        showDataDanhMucHD(hdsv.selectALllHoaDonBH());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private static String genMaHD() {
        int randomNumber = new Random().nextInt(10000000);
        String formattedNumber = String.format("%08d", randomNumber);
        String genSPCT = "HD" + formattedNumber;
        return genSPCT;
    }
    private void loadCBB(){
        cboHTTT.removeAllItems();
        cboLoaiKH.removeAllItems();
        cboHTTT.addItem("Chuyển khoản");
        cboHTTT.addItem("Tiền mặt");
        cboLoaiKH.addItem("Khách hàng lẻ");
        cboLoaiKH.addItem("Khách hàng thân thiết ");
    }
    private void showDataDanhMucSP(List<SanPhamChiTiet> listSPCT){
        modelSP.setRowCount(0);
        int index=1;
        for (SanPhamChiTiet spct : listSPCT) {
            Object row[]={false,index++,spct.getMaSPCT(),spct.getTenSPCT(),spct.getTenNhanHieu(),spct.getTenMauSac(),spct.getTenKichThuoc(),spct.getSoLuong(),spct.getGiaBan()};
            modelSP.addRow(row);
        }
    }
    private void fillDanhMucHD(){
        int selected= tblDanhMucHD.getSelectedRow();
        txtHoaDon.setText((String) tblDanhMucHD.getValueAt(selected, 1));
    }
     private void showDataDanhMucHD(List<Model_Hoa_Don>listHD){
        modelHD.setRowCount(0);
        int index=1;
        for (Model_Hoa_Don hd : listHD) {
            String trangthai="";
            if(hd.isTrangThai()){
                trangthai="Đã thanh toán";
            }else{
                trangthai="Chưa thanh toán";
            }
            Object row[]={index++,hd.getMaHD(),hd.getNguoitao(),hd.getTongTien(),hd.getNgayTao(),trangthai};
            modelHD.addRow(row);
        }
    }
      private void showDataGioHang1(List<GioHang1> list) {
        modelGH.setRowCount(0);
        int i = 0;
        for (GioHang1 gh1 : list) {
            i++;
            modelGH.addRow(new Object[]{i, gh1.getTenSP(),gh1.getDongia(),gh1.getSoLuong(), gh1.getThanhTien()});
        }
    }
       private void showDataGioHang1ByHD(List<GioHang1> list, String hoaDon) {
        modelGH.setRowCount(0);
        int i = 0;
        for (GioHang1 gh1 : list) {
            if (hoaDon.equalsIgnoreCase(gh1.getMaHoaDon())) {
                i++;
                modelGH.addRow(new Object[]{i, gh1.getTenSP(),gh1.getDongia(), gh1.getSoLuong(), gh1.getThanhTien()});
            }
        }
    }
     
        private void pushSPToCart() {
        //code new
        int selectedHD = tblDanhMucHD.getSelectedRow();
        if (selectedHD >= 0) {
            String trangThai = (String) tblDanhMucHD.getValueAt(selectedHD, 5);
            String maHD = (String) tblDanhMucHD.getValueAt(selectedHD, 1);
            if (trangThai.equals("Chưa thanh toán")) {
                int selected = tblDanhMucSP.getSelectedRow();
                if (selected >= 0) {
                    SanPhamChiTiet mctsp = listspct.get(selected);
                    Boolean choose = (Boolean) tblDanhMucSP.getValueAt(selected, 0);
                    if (choose == false) {
                        int confirm = JOptionPane.showConfirmDialog(this, "Bạn Muốn Chọn Sản Phẩm Này ?", "Xác Nhận", JOptionPane.YES_NO_OPTION);
                        if (confirm == JOptionPane.YES_OPTION) {
                            Model_SanPhamChiTiet ctsp = ctspsv.getCTSPByMa(mctsp.getMaSPCT());
                            int count=0;
                            int soLuongMua=Integer.parseInt(JOptionPane.showInputDialog("Mời Bạn Nhập Số Lượng:"));
                           /*if(soLuongMua<=0 || soLuongMua>99){
                                JOptionPane.showMessageDialog(this, "Số lượng chỉ được nhập từ 1-99");
                                count++;
                            }else{
                                JOptionPane.showMessageDialog(this, "Chỉ được nhập số");
                                count++;
                            }*/
                           
                            BigDecimal thanhTien = ctsp.getGiaBan().multiply(new BigDecimal(soLuongMua));
                            GioHang1 gh = new GioHang1(mctsp.getId(),mctsp.getTenSPCT(),mctsp.getGiaBan(), soLuongMua, thanhTien, maHD);
                            listGioHang.add(gh);
                            showDataGioHang1ByHD(listGioHang, maHD);
                        }
                        
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Hóa Đơn Này Đã Thanh Toán Không Thể Thêm SP1");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Bạn Chưa Chọn Hóa Đơn");
        }

    }
        
       
         //Create Hoa Don
   
    private void updateHD() {
        
        int selectedrow= tblDanhMucHD.getSelectedRow();
        if(selectedrow>=0){   
        String maHD= (String) tblDanhMucHD.getValueAt(selectedrow, 1);
        int loaiKH;
        if(cboLoaiKH.getSelectedItem().equals("Khách hàng lẻ")){
            loaiKH=0;
        }else{
            loaiKH=1;
        }
        int hTTT;
        if(cboHTTT.getSelectedItem().equals("Chuyển khoản")){
            hTTT=2;
        }else{
            hTTT=1;
        }
        
        BigDecimal tongTienKH = tinhTongCot(4);
        String ghichu=txtGhiChu.getText();
        HoaDonBH hdbh= new HoaDonBH(maHD, loaiKH,
                tongTienKH, ghichu, Auth.maNhanVien(), 2, hTTT);
                if(hdbh!=null){
                    int choice;
            choice= JOptionPane.showConfirmDialog(this,"Bạn có muốn thanh toán không", "Xác nhận",JOptionPane.YES_NO_OPTION);
            if(choice==JOptionPane.YES_OPTION){
                hdsv.update(hdbh);
                showDataDanhMucHD(hdsv.selectALllHoaDonBH());
                JOptionPane.showMessageDialog(this,"Thanh toán  thành công");
                }
            }
        }else{
            JOptionPane.showMessageDialog(this,"Bạn chưa chọn dòng");
        }       
}
   private void thanhToanBill() {
        int selected = tblDanhMucHD.getSelectedRow();
        int chon= tblDanhMucSP.getSelectedRow();
        //String ten=(String) tblGioHang.getValueAt(selected,1);
        //Model_SanPhamChiTiet ctsp=ctspsv.selectSPCTTenBH(ten);
        HoaDon hoadon= cthdsv.selectALllHoaDonByMa(txtHoaDon.getText());
        if (selected >= 0) {
            String maHD = (String) tblDanhMucHD.getValueAt(selected, 1);
            for (GioHang1 gh : listGioHang) {
                if(gh.getMaHoaDon().equalsIgnoreCase(maHD)){
                    HoaDonChiTiet hdct= new HoaDonChiTiet(gh.getIdCTSP(),hoadon.getIdHd(), gh.getSoLuong(), gh.getThanhTien());
                    cthdsv.createBill(hdct);
                     updateHD();
                   
                }
            }
        }
    }
   private void removeAlll(){
       int selected = tblDanhMucHD.getSelectedRow();
        if (selected >= 0) {
            String maHD = (String) tblDanhMucHD.getValueAt(selected, 1);
            String trangThaiHD = (String) tblDanhMucHD.getValueAt(selected, 5);
            if (trangThaiHD.equalsIgnoreCase("Chưa thanh toán")) {
                Iterator<GioHang1> itr = listGioHang.iterator();
                while (itr.hasNext()) {
                    GioHang1 gh = itr.next();
                    if (gh.getMaHoaDon().equals(maHD)) {
                        itr.remove();
                    }
                }
                showDataGioHang1ByHD(listGioHang, maHD);
                JOptionPane.showMessageDialog(this, "Xóa Tất Cả Sản Phẩm Thành Công!");
            } 
        } else {
            JOptionPane.showMessageDialog(this, "Bạn Chưa Chọn Hóa Đơn!");
        }  
   }
   private void removeAA(){
       int selected = tblGioHang.getSelectedRow();
       int se= tblDanhMucHD.getSelectedRow();
       if(selected>=0){
           String maHD= (String) tblDanhMucHD.getValueAt(se, 1);
           GioHang1 gh=listGioHang.get(selected);
           listGioHang.remove(gh);
           showDataGioHang1ByHD(listGioHang, maHD);
       }
   }
    private BigDecimal tinhTongCot(int columnIndex) {
        DefaultTableModel model = (DefaultTableModel) tblGioHang.getModel();
        int rowCount = model.getRowCount();
        BigDecimal tongtien = BigDecimal.ZERO;

        for (int row = 0; row < rowCount; row++) {
            Object value = model.getValueAt(row, columnIndex);
            if (value instanceof Number) {
                tongtien = tongtien.add(new BigDecimal(value.toString()));
            }
        }
        
        return tongtien;
    }
    private void createHoaDon() {
        Model_Hoa_Don hd = new Model_Hoa_Don();
        String maHD = this.genMaHD();
        hd.setMaHD(maHD);
        hd.setMaNV(""+Auth.maNhanVien());
        hd.setTrangThai(false);
        hd.setNgayTao(thoiGianHienTai);
        boolean createHD = hdsv.createBill(hd);
        if (createHD == true) {
            this.showDataDanhMucHD(hdsv.selectALllHoaDonBH());
            JOptionPane.showMessageDialog(this, "Tạo Hóa Đơn Thành Công!");
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jComboBox2 = new javax.swing.JComboBox<>();
        sanPhamChiTietSV1 = new com.raven.Service.SanPhamChiTietSV();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDanhMucHD = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblGioHang = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        WebcamPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblDanhMucSP = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtFind = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtGhiChu = new javax.swing.JTextField();
        btnThanhToan = new javax.swing.JButton();
        cboHTTT = new javax.swing.JComboBox<>();
        txtTienKH = new javax.swing.JTextField();
        txtHoaDon = new javax.swing.JTextField();
        lblTongTien = new javax.swing.JLabel();
        lblTongTienTT = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lblTienThua = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cboLoaiKH = new javax.swing.JComboBox<>();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("File");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("jMenu5");

        jMenu6.setText("jMenu6");

        jMenu7.setText("jMenu7");

        jMenu8.setText("jMenu8");

        jMenu9.setText("jMenu9");

        jMenu10.setText("jMenu10");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(915, 600));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh Mục Hóa Đơn", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        tblDanhMucHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã HĐ", "Mã NV", "Tổng tiền", "Ngày tạo", "Trạng thái"
            }
        ));
        tblDanhMucHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhMucHDMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDanhMucHD);
        if (tblDanhMucHD.getColumnModel().getColumnCount() > 0) {
            tblDanhMucHD.getColumnModel().getColumn(0).setMinWidth(40);
            tblDanhMucHD.getColumnModel().getColumn(0).setPreferredWidth(40);
            tblDanhMucHD.getColumnModel().getColumn(0).setMaxWidth(40);
            tblDanhMucHD.getColumnModel().getColumn(1).setMinWidth(80);
            tblDanhMucHD.getColumnModel().getColumn(1).setPreferredWidth(80);
            tblDanhMucHD.getColumnModel().getColumn(1).setMaxWidth(80);
            tblDanhMucHD.getColumnModel().getColumn(2).setMinWidth(60);
            tblDanhMucHD.getColumnModel().getColumn(2).setPreferredWidth(60);
            tblDanhMucHD.getColumnModel().getColumn(2).setMaxWidth(60);
            tblDanhMucHD.getColumnModel().getColumn(3).setMinWidth(90);
            tblDanhMucHD.getColumnModel().getColumn(3).setPreferredWidth(90);
            tblDanhMucHD.getColumnModel().getColumn(3).setMaxWidth(90);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Giỏ Hàng", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        tblGioHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Tên sản phẩm", "Đơn giá", "Số lượng", "Thành tiền", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblGioHang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblGioHangKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(tblGioHang);
        if (tblGioHang.getColumnModel().getColumnCount() > 0) {
            tblGioHang.getColumnModel().getColumn(0).setMinWidth(40);
            tblGioHang.getColumnModel().getColumn(0).setPreferredWidth(40);
            tblGioHang.getColumnModel().getColumn(0).setMaxWidth(40);
            tblGioHang.getColumnModel().getColumn(5).setMinWidth(20);
            tblGioHang.getColumnModel().getColumn(5).setPreferredWidth(20);
            tblGioHang.getColumnModel().getColumn(5).setMaxWidth(20);
        }

        jButton1.setBackground(new java.awt.Color(99, 146, 238));
        jButton1.setText("Xóa Sản Phẩm");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(99, 146, 238));
        jButton2.setText("Tạo Hóa Đơn");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(99, 146, 238));
        jButton3.setText("Xóa Tất Cả");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addGap(27, 27, 27)
                .addComponent(jButton3)
                .addGap(72, 72, 72))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        WebcamPanel.setBackground(new java.awt.Color(0, 0, 0));
        WebcamPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Barcode", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        WebcamPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh Sách Sản Phẩm", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        tblDanhMucSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "", "STT", "Mã sản phẩm", "Tên sản phẩm", "Nhãn hiệu", "Màu sắc", "Kích thước", "Số lượng tồn", "Đơn giá"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDanhMucSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhMucSPMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblDanhMucSP);
        if (tblDanhMucSP.getColumnModel().getColumnCount() > 0) {
            tblDanhMucSP.getColumnModel().getColumn(0).setMinWidth(20);
            tblDanhMucSP.getColumnModel().getColumn(0).setPreferredWidth(20);
            tblDanhMucSP.getColumnModel().getColumn(0).setMaxWidth(20);
            tblDanhMucSP.getColumnModel().getColumn(1).setMinWidth(40);
            tblDanhMucSP.getColumnModel().getColumn(1).setPreferredWidth(40);
            tblDanhMucSP.getColumnModel().getColumn(1).setMaxWidth(40);
            tblDanhMucSP.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Tìm Kiếm Sản Phẩm");

        txtFind.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtFind.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFindKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFind, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hóa Đơn", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông Tin Khách Hàng"));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel2.setText("Mã khách hàng :");

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel3.setText("Tên khách hàng :");

        jLabel4.setBackground(new java.awt.Color(230, 228, 228));

        jButton4.setBackground(new java.awt.Color(99, 146, 238));
        jButton4.setText("Chọn");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(99, 146, 238));
        jButton5.setText("Thay đổi");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addContainerGap())
        );

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel6.setText("Mã hóa đơn");

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel7.setText("Tổng tiền hàng :");

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel9.setText("Tiền khách đưa:");

        jLabel11.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel11.setText("Tổng tiền thanh toán:");

        jLabel12.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel12.setText("Tiền thừa :");

        jLabel13.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel13.setText("Hình thức thanh toán :");

        jLabel15.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel15.setText("Ghi chú :");

        txtGhiChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGhiChuActionPerformed(evt);
            }
        });

        btnThanhToan.setBackground(new java.awt.Color(99, 146, 238));
        btnThanhToan.setText("Thanh toán");
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        cboHTTT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboHTTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboHTTTActionPerformed(evt);
            }
        });

        txtHoaDon.setEnabled(false);

        lblTongTien.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblTongTien.setForeground(new java.awt.Color(255, 51, 51));
        lblTongTien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblTongTienMouseReleased(evt);
            }
        });

        lblTongTienTT.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblTongTienTT.setForeground(new java.awt.Color(255, 0, 51));
        lblTongTienTT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTongTienTTMouseClicked(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 51, 51));
        jLabel18.setText("VNĐ");

        jLabel19.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 51, 51));
        jLabel19.setText("VNĐ");

        jLabel20.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 51, 51));
        jLabel20.setText("VNĐ");

        jLabel16.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel16.setText("Loại khách hàng");

        cboLoaiKH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboLoaiKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLoaiKHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtGhiChu)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboHTTT, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cboLoaiKH, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(12, 12, 12)
                                                .addComponent(lblTongTienTT, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(lblTienThua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(txtTienKH, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))))
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel19))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(cboLoaiKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTongTienTT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTienKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(cboHTTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnThanhToan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lblTienThua, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(WebcamPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(WebcamPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtGhiChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGhiChuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGhiChuActionPerformed

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        createHoaDon();
    }//GEN-LAST:event_jButton2MouseClicked

    private void tblDanhMucHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhMucHDMouseClicked
        // TODO add your handling code here:
        int selected = tblDanhMucHD.getSelectedRow();
        if (selected >= 0) {
            String maHD = (String) tblDanhMucHD.getValueAt(selected, 1);
            showDataGioHang1ByHD(listGioHang, maHD);
        }
        fillDanhMucHD();
    }//GEN-LAST:event_tblDanhMucHDMouseClicked

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        // TODO add your handling code here:
        this.thanhToanBill();

    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void tblGioHangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblGioHangKeyReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_tblGioHangKeyReleased

    private void txtFindKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFindKeyReleased
        // TODO add your handling code here:
        if(!txtFind.getText().isEmpty()){
            String find= txtFind.getText();
            listspct=spctsv.selectSPCTByTen(find, find,find, find, find);
            showDataDanhMucSP(spctsv.selectSPCTByTen(find,find, find, find, find));
        }else{
            showDataDanhMucSP(spctsv.selectALll());
        }
    }//GEN-LAST:event_txtFindKeyReleased

    private void tblDanhMucSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhMucSPMouseClicked
        // TODO add your handling code here:
        pushSPToCart();
        lblTongTienTT.setText(tinhTongCot(4).toString());
        lblTongTien.setText(tinhTongCot(4).toString());
        

    }//GEN-LAST:event_tblDanhMucSPMouseClicked

    private void cboLoaiKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLoaiKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboLoaiKHActionPerformed

    private void cboHTTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboHTTTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboHTTTActionPerformed

    private void lblTongTienMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTongTienMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTongTienMouseReleased

    private void lblTongTienTTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTongTienTTMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTongTienTTMouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        KhachHangJDialog kh= new KhachHangJDialog();
        kh.setVisible(true);
        
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        removeAA();
         lblTongTienTT.setText(tinhTongCot(4).toString());
        lblTongTien.setText(tinhTongCot(4).toString());
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        removeAlll();
  lblTongTienTT.setText(tinhTongCot(4).toString());
        lblTongTien.setText(tinhTongCot(4).toString());
    }//GEN-LAST:event_jButton3MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel WebcamPanel;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JComboBox<String> cboHTTT;
    private javax.swing.JComboBox<String> cboLoaiKH;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblTienThua;
    private javax.swing.JLabel lblTongTien;
    private javax.swing.JLabel lblTongTienTT;
    private com.raven.Service.SanPhamChiTietSV sanPhamChiTietSV1;
    private javax.swing.JTable tblDanhMucHD;
    private javax.swing.JTable tblDanhMucSP;
    private javax.swing.JTable tblGioHang;
    private javax.swing.JTextField txtFind;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtHoaDon;
    private javax.swing.JTextField txtTienKH;
    // End of variables declaration//GEN-END:variables
}
